import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';
import StoreProvider from '@/app/StoreProvider';
import { ThemeProvider } from 'styled-components';
import { theme } from '@/config/themeConfig';

const dm_sans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className + 'box-border h-screen w-screen'}>
        <div className="bg-background h-full w-full overflow-auto">
          <Toaster
            position="top-center"
            gutter={8}
            toastOptions={{ className: 'w-96' }}
          />
          <StoreProvider>{children}</StoreProvider>
        </div>
      </body>
    </html>
  );
}
